name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout Builder Repo
        uses: actions/checkout@v4

      - name: Checkout App Repo
        uses: actions/checkout@v4
        with:
          repository: entitecdev3/ENT_B1_Cockpit
          token: ${{ secrets.PAT_TOKEN }}
          path: workspace/app

      - name: Checkout Custom Nodes Repo
        uses: actions/checkout@v4
        with:
          repository: entitecdev3/ENT_RED_CustomNodes
          token: ${{ secrets.PAT_TOKEN }}
          path: workspace/custom-nodes

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Build
        run: createBuild.bat
        shell: cmd

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: B1Cockpit-Installer
          path: output/*.exe
