name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout Builder Repo
        uses: actions/checkout@v4

      - name: Checkout App Repo
        uses: actions/checkout@v4
        with:
          repository: entitecdev3/ENT_B1_Cockpit
          token: ${{ secrets.PAT_TOKEN }}
          path: workspace/app

      - name: Checkout Custom Nodes Repo
        uses: actions/checkout@v4
        with:
          repository: entitecdev3/ENT_RED_CustomNodes
          token: ${{ secrets.PAT_TOKEN }}
          path: workspace/custom-nodes

      - name: Show Workspace Structure
        shell: cmd
        run: |
          echo ========================================
          echo ROOT
          echo ========================================
          dir

          echo.
          echo ========================================
          echo WORKSPACE
          echo ========================================
          dir workspace

          echo.
          echo ========================================
          echo APP REPO
          echo ========================================
          dir workspace\app

          echo.
          echo ========================================
          echo CUSTOM NODE REPO
          echo ========================================
          dir workspace\custom-nodes
