name: Move Important Files

on:
  push:
    branches:
      - main

jobs:
  move-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Move Files
        run: |
          mkdir -p target

          mv utils/package.json target/ || true
          mv utils/ui5.yaml target/ || true
          mv utils/moveToDist.js target/ || true

      - name: Show Result
        run: |
          echo "Files in target:"
          ls -la target
